# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serfa_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit',
            field=models.CharField(default='c', max_length=10),
            preserve_default=False,
        ),
    ]
