# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serfa_panel', '0003_usersensor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersensor',
            name='sensor',
        ),
    ]
