# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 17:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serfa_panel', '0004_remove_usersensor_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serfa_panel.Sensor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='usersensor',
            name='user',
        ),
        migrations.DeleteModel(
            name='usersensor',
        ),
    ]
