# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serfa_panel', '0005_auto_20170401_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='max',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='min',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
