# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serfa_panel', '0008_auto_20170406_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='key',
        ),
    ]
