# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serfa_panel', '0009_remove_unit_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='key',
            field=models.CharField(default='brak', max_length=20),
            preserve_default=False,
        ),
    ]
