# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serfa_panel', '0010_unit_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='max',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
    ]
