# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('serfa_panel', '0011_sensor_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='last_synchro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
